#!/bin/sh

here=`pwd`
output=$1

cd `dirname $0`
cd ..
PELICANSHOME=$PWD

cd $here

#-----------------------------------------------------------------------------
#    License
#-----------------------------------------------------------------------------
if [ "$2" != "accept" ]; then
#-----------------------------
echo "**********************************************************************"
echo "  PELICANS - Installation under the condition that:"
echo "      1. the license is read,"
echo "      2. the terms of the license are accepted."
echo "**********************************************************************"
echo "Do you want to proceed? (y/n)"
read X
if [ "$X" != "y" ]; then
   exit 1
fi
more Licence_CeCILL-C_V1-en.txt
echo "**********************************************************************"
echo "  You may want to re-read the CeCILL-C license agreement:"
echo "      1. in the file  Licence_CeCILL-C_V1-en.txt (english),"
echo "      2. in the file  Licence_CeCILL-C_V1-fr.txt (french),"
echo "      3. at the URL  http://www.cecill.info (with additional infos)."
echo "**********************************************************************"
echo "Do you accept the terms of the CeCILL-C license? (y/n)"
read X
if [ "$X" != "y" ]; then 
   exit 1 
fi
echo "**********************************************************************"
echo "  PELICANS is the copyrighted work (1995-2010) of:"
echo "           Institut de Radioprotection et de Sureté Nucléaire (IRSN)"
echo "  This software is an application framework, with a set of integrated"
echo "  reusable components, whose purpose is to simplify the task of"
echo "  developing softwares of numerical mathematics and"
echo "  scientific computing."
echo "**********************************************************************"
echo "Do you want to proceed? (y/n)"
read X
if [ "$X" != "y" ]; then 
   exit 1 
fi
echo "**********************************************************************"
echo "  PELICANS is governed by the CeCILL-C license under French law and"
echo "  abiding by the rules of distribution of free software."
echo "  You can use, modify and/or redistribute the software under the terms"
echo "  of the CeCILL-C license as circulated by CEA, CNRS and INRIA at the"
echo "  following URL http://www.cecill.info."
echo "**********************************************************************"
echo "Do you want to proceed? (y/n)"
read X
if [ "$X" != "y" ]; then 
   exit 1 
fi
echo "**********************************************************************"
echo "  As a counterpart to the access to the source code and rights to copy,"
echo "  modify and redistribute granted by the license, users are provided"
echo "  only with a limited warranty and the software's author, the holder"
echo "  of the economic rights, and the successive licensors have only"
echo "  limited liability."
echo "**********************************************************************"
echo "Do you want to proceed? (y/n)"
read X
if [ "$X" != "y" ]; then 
   exit 1 
fi
echo "**********************************************************************"
echo "  In this respect, the user's attention is drawn to the risks"
echo "  associated with loading, using, modifying and/or developing or"
echo "  reproducing the software by the user in light of its specific status"
echo "  of free software, that may mean that it is complicated to manipulate,"
echo "  and that also therefore means that it is reserved for developers and"
echo "  experienced professionals having in-depth computer knowledge."
echo "  Users are therefore encouraged to load and test the software's"
echo "  suitability as regards their requirements in conditions enabling"
echo "  the security of their systems and/or data to be ensured and,"
echo "  more generally, to use and operate it in the same conditions as"
echo "  regards security."
echo "**********************************************************************"
echo "Do you want to proceed? (y/n)"
read X
if [ "$X" != "y" ]; then 
   exit 1 
fi
echo "**********************************************************************"
echo "  The fact that you are proceeding further means that you have had"
echo "  knowledge of the CeCILL-C license and that you accept its terms."
echo "**********************************************************************"
echo "Do you want to proceed? (y/n)"
read X
if [ "$X" != "y" ]; then 
   exit 1
fi
echo "**********************************************************************"
#---
fi
#---

#-----------------------------------------------------------------------------
#    Contruct init.csh and init.sh
#-----------------------------------------------------------------------------
echo Construction of $output.csh
echo setenv PELICANSHOME $PELICANSHOME > $output.csh
echo source \$PELICANSHOME/bin/setvar.csh >> $output.csh

echo Construction of $output.sh
echo PELICANSHOME=$PELICANSHOME > $output.sh
echo export PELICANSHOME  >> $output.sh
echo . \$PELICANSHOME/bin/setvar.sh >> $output.sh


