/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class data_jni_PModule */

#ifndef _Included_data_jni_PModule
#define _Included_data_jni_PModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     data_jni_PModule
 * Method:    initialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_data_jni_PModule_initialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     data_jni_PModule
 * Method:    createFromFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_createFromFile__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    createFromFile
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_createFromFile__Ljava_lang_String_2J
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     data_jni_PModule
 * Method:    createFromString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_createFromString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_data_jni_PModule_name
  (JNIEnv *, jclass, jint);

/*
 * Class:     data_jni_PModule
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_data_jni_PModule_destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     data_jni_PModule
 * Method:    parent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_parent
  (JNIEnv *, jclass, jint);

/*
 * Class:     data_jni_PModule
 * Method:    nbModules
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_nbModules
  (JNIEnv *, jclass, jint);

/*
 * Class:     data_jni_PModule
 * Method:    getModule
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_getModule__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     data_jni_PModule
 * Method:    getModule
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_getModule__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    addModule
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_addModule
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    removeModule
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_removeModule__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     data_jni_PModule
 * Method:    removeModule
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_removeModule__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    nbData
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_nbData
  (JNIEnv *, jclass, jint);

/*
 * Class:     data_jni_PModule
 * Method:    getData
 * Signature: (IILdata/jni/PData;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_getData__IILdata_jni_PData_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     data_jni_PModule
 * Method:    getData
 * Signature: (ILjava/lang/String;Ldata/jni/PData;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_getData__ILjava_lang_String_2Ldata_jni_PData_2
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     data_jni_PModule
 * Method:    ngetData
 * Signature: (II)Ldata/jni/PData;
 */
JNIEXPORT jobject JNICALL Java_data_jni_PModule_ngetData
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     data_jni_PModule
 * Method:    nbVariable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_nbVariable
  (JNIEnv *, jclass, jint);

/*
 * Class:     data_jni_PModule
 * Method:    ngetVariable
 * Signature: (II)Ldata/jni/PData;
 */
JNIEXPORT jobject JNICALL Java_data_jni_PModule_ngetVariable
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     data_jni_PModule
 * Method:    addData
 * Signature: (ILdata/jni/PData;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_addData
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     data_jni_PModule
 * Method:    removeData
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_removeData__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     data_jni_PModule
 * Method:    removeData
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_data_jni_PModule_removeData__ILjava_lang_String_2
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    evaluate_entry
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_data_jni_PModule_evaluate_1entry
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    evaluate_expression
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_data_jni_PModule_evaluate_1expression
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     data_jni_PModule
 * Method:    getRegisteredExpressions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_data_jni_PModule_getRegisteredExpressions
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
