
lcomment = *, 1
lcomment += *, 73

kw1  = ASSIGN, BACKSPACE, BLOCK DATA, CALL, CHARACTER, CLOSE, COMMON
kw1 += COMPLEX, CONTINUE, DATA, DIMENSION, DO, DOUBLE PRECISION, ELSE
kw1 += ELSEIF, END, ENDIF, ENDFILE, ENTRY, EQUIVALENCE, EXTERNAL, FORMAT, FUNCTION
kw1 += GO TO, GOTO, IF, IMPLICIT, INQUIRE, INTEGER, INTRINSIC, LOGICAL
kw1 += OPEN, PARAMETER, PAUSE, PRINT, PROGRAM, READ, REAL, RETURN, THEN
kw1 += REWIND, SAVE, STOP, SUBROUTINE, WRITE, NONE, .TRUE., .FALSE.

kw1 += .NOT.
kw3 = LEN, TRIM

kw2 = #include, #define, #ifdef, #ifndef, #endif, #else, #if, defined, #pragma
