include f

casesensitive = 0

lcomment = !

kw1 += MODULE, PROCEDURE, INTERFACE, SELECT, CASE, DEFAULT, WHILE, CYCLE, EXIT
kw1 += CONTAINS, PUBLIC, PRIVATE, ASSIGNMENT, ALLOCATE, DEALLOCATE

kw2 += OPTIONAL, PRESENT, INTENT, IN, OUT, INOUT, TYPE, SEQUENCE, POINTER
kw2 += ALLOCATABLE, NULLIFY

kw3 += ABS, AIMAG, AINT, ANINT, CMPLX, CONJG, DBLE, DIM, DPROD, INT, MAX
kw3 += MIN, MOD, NINT, REAL, SIGN
kw3 += ACOS, ASIN, ATAN, ATAN2, COS, COSH, EXP, LOG, LOG10, SIN, SINH
kw3 += SQRT, TAN, TANH
kw3 += ACHAR, ADJUSTL, ADJUSTR, CHAR, IACHAR, ICHAR, INDEX, LEN_TRIM
kw3 += LGE, LGT, LLE, LLT, REPEAT, SCAN, VERIFY
kw3 += KIND, SELECTED_INT_KIND, SELECTED_REAL_KIND, TRANSFER
